name: Deploy dist
# on: push
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
            #   run: |
            #     echo "cloning repo.."
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/${{github.repository}}.git
              uses: actions/checkout@v6
            - name: Install Node 24
              uses: actions/setup-node@v6
              with: 
                node-version: 24